# Generated by Django 5.1.4 on 2025-08-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='run',
            name='page_objects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='run',
            name='scenarios',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='run',
            name='test_results',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='artifact_type',
            field=models.CharField(choices=[('pom', 'Page Object Model'), ('test', 'Test File'), ('screenshot', 'Screenshot'), ('video', 'Video'), ('log', 'Log File'), ('junit', 'JUnit XML'), ('summary', 'Summary'), ('config', 'Configuration'), ('package', 'Package'), ('readme', 'README'), ('gitignore', 'Git Ignore'), ('tsconfig', 'TypeScript Config')], max_length=20),
        ),
    ]
